 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/uni_modules", type: :request do
  # UniModule. As you add validations to UniModule, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      UniModule.create! valid_attributes
      get uni_modules_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      uni_module = UniModule.create! valid_attributes
      get uni_module_url(uni_module)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_uni_module_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      uni_module = UniModule.create! valid_attributes
      get edit_uni_module_url(uni_module)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new UniModule" do
        expect {
          post uni_modules_url, params: { uni_module: valid_attributes }
        }.to change(UniModule, :count).by(1)
      end

      it "redirects to the created uni_module" do
        post uni_modules_url, params: { uni_module: valid_attributes }
        expect(response).to redirect_to(uni_module_url(UniModule.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new UniModule" do
        expect {
          post uni_modules_url, params: { uni_module: invalid_attributes }
        }.to change(UniModule, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post uni_modules_url, params: { uni_module: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested uni_module" do
        uni_module = UniModule.create! valid_attributes
        patch uni_module_url(uni_module), params: { uni_module: new_attributes }
        uni_module.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the uni_module" do
        uni_module = UniModule.create! valid_attributes
        patch uni_module_url(uni_module), params: { uni_module: new_attributes }
        uni_module.reload
        expect(response).to redirect_to(uni_module_url(uni_module))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        uni_module = UniModule.create! valid_attributes
        patch uni_module_url(uni_module), params: { uni_module: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested uni_module" do
      uni_module = UniModule.create! valid_attributes
      expect {
        delete uni_module_url(uni_module)
      }.to change(UniModule, :count).by(-1)
    end

    it "redirects to the uni_modules list" do
      uni_module = UniModule.create! valid_attributes
      delete uni_module_url(uni_module)
      expect(response).to redirect_to(uni_modules_url)
    end
  end
end
